### ISSUE TITLE
Tarantool memcached doesn't start expire-fiber in docker

### ISSUE THREAD

**Issue by fry256** [tarantool/memcached#52] opened 2020-01-15 07:28 UTC
Hi!
When I start tarantool with memcached module in docker I have got a message:
```
2020-01-15 06:56:45.388 [1] main/101/tarantool-entrypoint.lua expiration.c:114 E> Can't start the expire fiber
2020-01-15 06:56:45.388 [1] main/101/tarantool-entrypoint.lua expiration.c:115 E> fio: No such file or directory
2020-01-15 06:56:45.389 [1] main/101/tarantool-entrypoint.lua expiration.c:114 E> Can't start the expire fiber
2020-01-15 06:56:45.390 [1] main/101/tarantool-entrypoint.lua expiration.c:115 E> fio: No such file or directory
```
For launch I used next settings:
```
#!/usr/bin/env tarantool
memcached = require('memcached')

box.cfg{
  read_only   = false;

  memtx_memory         = 2 * 1024 * 1024 * 1024;  -- 2Gb
  memtx_min_tuple_size = 36;
  memtx_max_tuple_size = 2 * 1024 * 1024;  -- 2Mb

  wal_mode             = "write";
  wal_max_size         = 256 * 1024 * 1024;  -- 256Mb
  checkpoint_interval  = 60 * 60;
  checkpoint_count     = 10;
  force_recovery       = true;

  log_level    = 5;
  log_nonblock = true;
}

opts = {
    expire_enabled = true;
}

instance = memcached.create('my_instance', '0.0.0.0:11211', opts)
```
And command:
```
docker run --name mytesttarantool -p3301:3301 -v ${PWD}:/opt/tarantool tarantool/tarantool tarantool /opt/tarantool/app.lua
```
if I start the app inside the container:
```
docker exec -it mytesttarantool sh
tarantool /opt/tarantool/app.lua
```
Expire fiber starts OK:
```
2020-01-15 07:01:57.269 [100] main/112/__mc_my_instance_expire I> Memcached expire fiber started
```
But if I try to watch fiber.info even after several hours I always see the same result:
```
  113:
    csw: 0
    backtrace:
    - C: '#0  0 in +67'
    fid: 113
    memory:
      total: 516432
      used: 0
    name: __mc_my_instance_expire
```
It seems, that fiber doesn't work at all.

**Comment by LeonidVas** [comment] 2020-05-18 16:10
The cause of the first problem is an error which was set to diag in https://github.com/tarantool/docker/blob/master/files/tarantool-entrypoint.lua#L173 when checking config file (/etc/tarantool/config.yml) to the existing one.
This has been fixed in https://github.com/tarantool/memcached/commit/a46623c5ac323f79a85df2d2afbe4b56dc613231 and will be fixed in the docker image after memcached is updated in rocks.
The second problem has not been reproduced.
For testing, I used the image https://hub.docker.com/layers/tarantool/tarantool/1.x-centos7/images/sha256-862ddc522a843cbda2c85fb96f3dd66ba7a13cab78ae04268ff878326e0dcedb?context=explore .

**Comment by LeonidVas** [comment] 2020-05-18 16:21
Memcached release is planned after fix for https://github.com/tarantool/memcached/issues/53 is merged to master.

**Comment by Totktonada** [comment] 2020-06-03 19:35
Duplicate of #44.

I'll release the module soon and will ask colleagues to update it in our docker images. Hope everything will be done on the week.

**Closed by Totktonada** 2020-06-03 19:35 UTC

**Comment by Totktonada** [comment] 2020-06-03 20:22
The module is released: https://github.com/tarantool/memcached/releases/tag/1.0.1

Waiting for docker images update: https://github.com/tarantool/docker/issues/151
